name: Flutter CI

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.4'
          cache: true
      - name: Install packages (Root)
        run: flutter pub get
      - name: Run analyzer (Root)
        run: flutter analyze
      - name: Run tests (Root)
        run: flutter test --coverage
      
      - name: Install packages (F-Droid)
        run: cd app_fdroid && flutter pub get
      - name: Run analyzer (F-Droid)
        run: cd app_fdroid && flutter analyze

      - name: Install packages (Play Store)
        run: cd app_playstore && flutter pub get
      - name: Run analyzer (Play Store)
        run: cd app_playstore && flutter analyze
