name: Update Contributors JSON

on:
  schedule:
    - cron: '0 0 * * 0'  # weekly
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@vv4
        with:
          fetch-depth: 0

      - name: Check for changes
        id: check_changes
        if: github.event_name == 'schedule'
        run: |
          LAST_UPDATE_COMMIT=$(git log --author="github-actions[bot]" --grep="Update contributors.json in assets" -n 1 --pretty=format:%H)
          if [ -z "$LAST_UPDATE_COMMIT" ]; then
            echo "No previous contributor update found. Running job."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            if git rev-list $LAST_UPDATE_COMMIT..HEAD --count | grep -q '^[1-9]'; then
              echo "Changes found since last contributor update. Running job."
              echo "has_changes=true" >> $GITHUB_OUTPUT
            else
              echo "No changes found since last contributor update. Skipping job."
              echo "has_changes=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Install jq
        if: github.event_name == 'workflow_dispatch' || steps.check_changes.outputs.has_changes == 'true'
        run: sudo apt-get install -y jq

      - name: Fetch, sort & clean contributor list
        if: github.event_name == 'workflow_dispatch' || steps.check_changes.outputs.has_changes == 'true'
        run: |
          mkdir -p assets
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/contributors)
          if echo "$RESPONSE" | jq 'type' | grep -q '"array"'; then
            echo "$RESPONSE" | jq '[.[] 
              | select((.login | test("bot") | not) and (.login != "actions-user")) 
                | { 
                    login: .login, 
                    contributions: .contributions, 
                    avatar_url: .avatar_url, 
                    html_url: .html_url 
                  }] 
              | sort_by(-.contributions)' > assets/contributors.json
          else
            echo "$RESPONSE" > assets/contributors.json
            echo "Warning: GitHub API did not return an array. See assets/contributors.json for details."
          fi

      - name: Commit updated JSON
        if: github.event_name == 'workflow_dispatch' || steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add assets/contributors.json
          git diff --cached --quiet || git commit -m "Update contributors.json in assets"
          git push
