name: Update Contributors JSON

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'  # weekly
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch, sort & clean contributor list
        run: |
          mkdir -p assets
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/contributors)
          if echo "$RESPONSE" | jq 'type' | grep -q '"array"'; then
            echo "$RESPONSE" | jq '[.[] 
              | select((.login | test("bot") | not) and (.login != "actions-user")) 
              | { 
                  login: .login, 
                  contributions: .contributions, 
                  avatar_url: .avatar_url, 
                  html_url: .html_url 
                }] 
              | sort_by(-.contributions)' > assets/contributors.json
          else
            echo "$RESPONSE" > assets/contributors.json
            echo "Warning: GitHub API did not return an array. See assets/contributors.json for details."
          fi

      - name: Commit updated JSON
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add assets/contributors.json
          git diff --cached --quiet || git commit -m "Update contributors.json in assets"
          git push
